name: smart_remove
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #--------------- PACKAGES START --------------#

  cupertino_icons: ^1.0.6

  # Firebase Packages
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0

  # Logins Packages
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0

  # Utilities
  image_picker: ^1.1.2
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  iconsax:
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  awesome_snackbar_content: ^0.1.3
  screenshot: ^3.0.0
  image_compare_slider: ^2.8.0
  image_gallery_saver: ^2.0.3
  open_file: ^3.3.2


  #external_app_launcher: ^4.0.0
  image: ^4.2.0
  flutter_colorpicker: ^1.1.0
  device_info_plus: ^10.1.0


#--------------- PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  # change Icon of App
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS --------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/licenses/
    - assets/svg/

  #--------------- LOCAL FONTS --------------#
  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Light.ttf
          weight: 400
        - asset: assets/fonts/InriaSans-Regular.ttf
          weight: 600
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 800
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf




  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
