// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_KEY',
    appId: '1:335087812220:web:f823f3ab348ba2d3cad3f9',
    messagingSenderId: '335087812220',
    projectId: 'smart-remove-f418d',
    authDomain: 'smart-remove-f418d.firebaseapp.com',
    storageBucket: 'smart-remove-f418d.appspot.com',
    measurementId: 'G-ZHXG7GDLTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_KEY',
    appId: '1:335087812220:android:bd05f217b61a0d52cad3f9',
    messagingSenderId: '335087812220',
    projectId: 'smart-remove-f418d',
    storageBucket: 'smart-remove-f418d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_KEY',
    appId: '1:335087812220:ios:1ec7e3ccbe92c055cad3f9',
    messagingSenderId: '335087812220',
    projectId: 'smart-remove-f418d',
    storageBucket: 'smart-remove-f418d.appspot.com',
    iosBundleId: 'com.hk.smartRemove',
  );
}
